version: '3.8'

services:
    postgres-pi2:
        image: postgres:17.2
        container_name: postgres-pi2
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
        ports:
            - '${POSTGRES_DB_PORT}:5432'
        networks:
            - app-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            DATABASE_URL: ${DATABASE_URL}
        ports:
            - "3001:3001"
            - "5555:5555"
        depends_on:
            postgres-pi2:
                condition: service_healthy

networks:
    app-network:
        driver: bridge
